//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace btl.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ChiTietHoaDon
    {
        [Display(Name = "Mã HĐ")]
        public int MaHD { get; set; }
        [Display(Name = "Mã SP")]
        public int MaSP { get; set; }
        [Display(Name = "Số Lượng")]
        public int SoLuong { get; set; }
        [Display(Name = "Đơn Giá")]
        public double DonGia { get; set; }
    
        public virtual HoaDon HoaDon { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
