//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace btl.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            this.ChiTietHoaDons = new HashSet<ChiTietHoaDon>();
            this.ThongSoSanPhams = new HashSet<ThongSoSanPham>();
        }

        [Display(Name = "Mã SP")]
        public int MaSP { get; set; }
        [Display(Name = "Loại Sản Phẩm")]
        [Required(ErrorMessage = "{0} không được để trống !")]
        public int MaLSP { get; set; }
        [Display(Name = "Tên Sản Phẩm")]
        [StringLength(50,ErrorMessage = "{0} không quá 50 kí tự !")]
        [Required(ErrorMessage = "{0} không được để trống !")]
        public string TenSP { get; set; }
        [Display(Name = "Đơn Giá")]
        [Required(ErrorMessage = "{0} không được để trống !")]
        [Range(0,int.MaxValue,ErrorMessage = "{0} phải lớn hơn hoặc bằng 0")]
        public int DonGia { get; set; }
        [Display(Name = "Số Lượng")]
        [Required(ErrorMessage = "{0} không được để trống !")]
        [Range(0, int.MaxValue, ErrorMessage = "{0} phải lớn hơn hoặc bằng 0")]
        public int SoLuong { get; set; }
        [Display(Name = "Khuyến Mại")]
        [Required(ErrorMessage = "{0} không được để trống !")]
        [Range(0, int.MaxValue, ErrorMessage = "{0} phải lớn hơn hoặc bằng 0")]
        public int KhuyenMai { get; set; }
        [Display(Name = "Trạng Thái")]
        public bool Active { get; set; }
        [Display(Name = "Hình Ảnh")]
        [StringLength(200, ErrorMessage = "{0} không quá 200 kí tự !")]
        public string HinhAnh { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietHoaDon> ChiTietHoaDons { get; set; }
        public virtual LoaiSanPham LoaiSanPham { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThongSoSanPham> ThongSoSanPhams { get; set; }
    }
}
