//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace btl.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ThongSoSanPham
    {
        [Display(Name = "Mã SP")]
        public int MaSP { get; set; }
        [Display(Name = "Mã Thông Số Kĩ Thuật")]
        public int MaTSKT { get; set; }
        [Display(Name = "Giá Trị")]
        [StringLength(50, ErrorMessage = "{0} không quá 50 kí tự !")]
        [Required(ErrorMessage = "{0} không được để trống !")]
        public string GiaTri { get; set; }
    
        public virtual SanPham SanPham { get; set; }
        public virtual ThongSoKiThuat ThongSoKiThuat { get; set; }
    }
}
